### ISSUE TITLE
macOS fails to copy utf8

### ISSUE THREAD

**Issue by ghost** [shlomif/Clipboard#6]
`my $data = Clipboard->paste;`

fails to copy from Pasteboard characters such as üäà etc. Tested on Mojave.

**Comment by shlomif** [comment]
Hi! Sorry for the late reply.  I don't know how to fix it (and I don't have a macOS box nor do I approve of their non-open/non-free nature: https://www.youtube.com/watch?v=uCeMZccDMA0 ; https://www.shlomifish.org/humour/Summerschool-at-the-NSA/ ) but I"ll accept pullreqs or patches to fix it due to [reality to be commanded must be obeyed](http://shlomifishswiki.branchable.com/Self-Sufficiency/)

**Comment by shlomif** [comment]
Closing as stale. I can reopen if there's progress; also see https://metacpan.org/pod/Mac::Pasteboard
